// Generated by gencpp from file plumbing_server_client/addints.msg
// DO NOT EDIT!


#ifndef PLUMBING_SERVER_CLIENT_MESSAGE_ADDINTS_H
#define PLUMBING_SERVER_CLIENT_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <plumbing_server_client/addintsRequest.h>
#include <plumbing_server_client/addintsResponse.h>


namespace plumbing_server_client
{

struct addints
{

typedef addintsRequest Request;
typedef addintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addints
} // namespace plumbing_server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plumbing_server_client::addints > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::plumbing_server_client::addints&) { return value(); }
};

template<>
struct DataType< ::plumbing_server_client::addints > {
  static const char* value()
  {
    return "plumbing_server_client/addints";
  }

  static const char* value(const ::plumbing_server_client::addints&) { return value(); }
};


// service_traits::MD5Sum< ::plumbing_server_client::addintsRequest> should match
// service_traits::MD5Sum< ::plumbing_server_client::addints >
template<>
struct MD5Sum< ::plumbing_server_client::addintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::addints >::value();
  }
  static const char* value(const ::plumbing_server_client::addintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::addintsRequest> should match
// service_traits::DataType< ::plumbing_server_client::addints >
template<>
struct DataType< ::plumbing_server_client::addintsRequest>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::addints >::value();
  }
  static const char* value(const ::plumbing_server_client::addintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plumbing_server_client::addintsResponse> should match
// service_traits::MD5Sum< ::plumbing_server_client::addints >
template<>
struct MD5Sum< ::plumbing_server_client::addintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::addints >::value();
  }
  static const char* value(const ::plumbing_server_client::addintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::addintsResponse> should match
// service_traits::DataType< ::plumbing_server_client::addints >
template<>
struct DataType< ::plumbing_server_client::addintsResponse>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::addints >::value();
  }
  static const char* value(const ::plumbing_server_client::addintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMBING_SERVER_CLIENT_MESSAGE_ADDINTS_H
